const lessonTitle = "年糕";

const lessonData = [
    // ===== 第1段 =====
    ["小时候", "xiǎo shí hou", "When I was young", "Semasa kecil"],
    ["，", "", "", ""],
    ["曾", "céng", "once", "pernah"],
    ["有", "yǒu", "had", "ada"],
    ["一段时间", "yí duàn shí jiān", "a period of time", "satu tempoh masa"],
    ["寄居", "jì jū", "stayed with", "tinggal bersama"],
    ["在", "zài", "at", "di"],
    ["祖母", "zǔ mǔ", "grandmother", "nenek"],
    ["的", "de", "", ""],
    ["家", "jiā", "home", "rumah"],
    ["。", "", "", ""],
    ["每年", "měi nián", "Every year", "Setiap tahun"],
    ["岁暮", "suì mù", "year-end", "akhir tahun"],
    ["，", "", "", ""],
    ["喧喧嚷嚷", "xuān xuān rǎng rǎng", "bustling and noisy", "riuh-rendah"],
    ["地", "de", "", ""],
    ["准备", "zhǔn bèi", "preparing", "menyediakan"],
    ["过年", "guò nián", "for the New Year", "sambutan Tahun Baru"],
    ["的", "de", "", ""],
    ["当儿", "dāng r", "at that time", "pada masa itu"],
    ["，", "", "", ""],
    ["我最爱的", "wǒ zuì ài de", "what I loved most", "yang paling saya suka"],
    ["，", "", "", ""],
    ["便是", "biàn shì", "was", "ialah"],
    ["看祖母", "kàn zǔ mǔ", "watching grandmother", "melihat nenek"],
    ["做年糕", "zuò nián gāo", "making New Year cake", "membuat kuih Tahun Baru"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    ["尽管", "jǐn guǎn", "Although", "Walaupun"],
    ["市面上", "shì miàn shàng", "in the market", "di pasaran"],
    ["有", "yǒu", "there were", "ada"],
    ["现成的", "xiàn chéng de", "ready-made", "sedia"],
    ["糯米粉", "nuò mǐ fěn", "glutinous rice flour", "tepung pulut"],
    ["出售", "chū shòu", "for sale", "dijual"],
    ["，", "", "", ""],
    ["可是", "kě shì", "but", "tetapi"],
    ["，", "", "", ""],
    ["祖母", "zǔ mǔ", "grandmother", "nenek"],
    ["担心", "dān xīn", "worried", "bimbang"],
    ["那些", "nà xiē", "those", "tepung itu"],
    ["糯米粉", "nuò mǐ fěn", "rice flour", "tepung pulut"],
    ["掺进", "chān jìn", "mixed with", "dicampur dengan"],
    ["别的", "bié de", "other", "lain"],
    ["杂质", "zá zhì", "impurities", "bahan asing"],
    ["，", "", "", ""],
    ["所以", "suǒ yǐ", "so", "maka"],
    ["，", "", "", ""],
    ["每年", "měi nián", "every year", "setiap tahun"],
    ["总", "zǒng", "always", "selalu"],
    ["买", "mǎi", "bought", "membeli"],
    ["大包大包", "dà bāo dà bāo", "big bags of", "beg-beg besar"],
    ["的", "de", "", ""],
    ["糯米", "nuò mǐ", "glutinous rice", "beras pulut"],
    ["回来", "huí lái", "back", "pulang"],
    ["自己磨", "zì jǐ mó", "to grind herself", "kisar sendiri"],
    ["。", "", "", ""],
    ["一面", "yí miàn", "While", "Sambil"],
    ["慢慢地", "màn màn de", "slowly", "perlahan-lahan"],
    ["转着", "zhuǎn zhe", "turning", "memusingkan"],
    ["那", "nà", "that", "batu kisar"],
    ["古老质朴", "gǔ lǎo zhì pǔ", "ancient and simple", "yang kuno dan sederhana"],
    ["的", "de", "", ""],
    ["小石磨", "xiǎo shí mò", "small stone mill", "kecil itu"],
    ["，", "", "", ""],
    ["一面", "yí miàn", "while", "sambil"],
    ["脸带虔诚地", "liǎn dài qián chéng de", "with a pious face", "dengan wajah khusyuk"],
    ["喃喃细语", "nán nán xì yǔ", "murmuring softly", "berbisik perlahan"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["年糕年糕年年高", "nián gāo nián gāo nián nián gāo", "New Year cake, year by year higher", "Kuih tahun baru, tahun demi tahun lebih tinggi"],
    ["。”", "", "", ""],
    ["把愿望", "bǎ yuàn wàng", "Putting wishes", "Meletakkan harapan"],
    ["寄托在", "jì tuō zài", "into", "dalam"],
    ["传统食品里", "chuán tǒng shí pǐn lǐ", "traditional food", "makanan tradisional"],
    ["的", "de", "", ""],
    ["这种", "zhè zhǒng", "this kind of", "jenis ini"],
    ["美丽情愫", "měi lì qíng sù", "beautiful sentiment", "perasaan yang indah"],
    ["，", "", "", ""],
    ["深深地", "shēn shēn de", "deeply", "secara mendalam"],
    ["触动着", "chù dòng zhe", "touched", "menyentuh"],
    ["我的心", "wǒ de xīn", "my heart", "hati saya"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    ["磨好了的", "mó hǎo le de", "After grinding", "Selepas dikisar"],
    ["糯米粉", "nuò mǐ fěn", "rice flour", "tepung pulut"],
    ["，", "", "", ""],
    ["像白雪一样", "xiàng bái xuě yí yàng", "like white snow", "seperti salji putih"],
    ["，", "", "", ""],
    ["高高地", "gāo gāo de", "high", "tinggi-tinggi"],
    ["堆着", "duī zhe", "piled up", "bertimbun"],
    ["。", "", "", ""],
    ["祖母", "zǔ mǔ", "Grandmother", "Nenek"],
    ["在", "zài", "added", "menambahkan"],
    ["糯米粉中", "nuò mǐ fěn zhōng", "to the rice flour", "ke dalam tepung pulut"],
    ["加入水", "jiā rù shuǐ", "water", "air"],
    ["、", "", "", ""],
    ["加入椰糖", "jiā rù yē táng", "palm sugar", "gula melaka"],
    ["，", "", "", ""],
    ["搅匀", "jiǎo yún", "mixed evenly", "kacau rata"],
    ["；", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian"],
    ["，", "", "", ""],
    ["在", "zài", "in", "di"],
    ["圆型的铁罐里", "yuán xíng de tiě guàn lǐ", "round tin cans", "dalam tin bulat"],
    ["妥帖地", "tuǒ tiē de", "neatly", "dengan kemas"],
    ["铺上", "pū shàng", "laid", "melapik"],
    ["剪成圆形", "jiǎn chéng yuán xíng", "round-cut", "dipotong bulat"],
    ["的", "de", "", ""],
    ["香蕉叶", "xiāng jiāo yè", "banana leaves", "daun pisang"],
    ["，", "", "", ""],
    ["小心翼翼地", "xiǎo xīn yì yì de", "carefully", "dengan berhati-hati"],
    ["倒入", "dào rù", "poured in", "menuangkan"],
    ["拌好了的", "bàn hǎo le de", "mixed", "yang telah dikacau"],
    ["糯米粉", "nuò mǐ fěn", "rice flour", "tepung pulut"],
    ["，", "", "", ""],
    ["再把", "zài bǎ", "then", "kemudian"],
    ["铁罐", "tiě guàn", "tins", "tin-tin"],
    ["一只一只地", "yì zhī yì zhī de", "one by one", "satu demi satu"],
    ["搁在", "gē zài", "placed on", "diletakkan di"],
    ["炭炉", "tàn lú", "charcoal stove", "dapur arang"],
    ["上面的", "shàng miàn de", "", ""],
    ["蒸笼里", "zhēng lóng lǐ", "steamer", "dalam pengukus"],
    ["，", "", "", ""],
    ["蒸上", "zhēng shàng", "steamed for", "dikukus selama"],
    ["几个小时", "jǐ gè xiǎo shí", "several hours", "beberapa jam"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    ["蒸好的", "zhēng hǎo de", "Steamed", "Selepas dikukus"],
    ["年糕", "nián gāo", "New Year cake", "kuih Tahun Baru"],
    ["，", "", "", ""],
    ["软滑如水", "ruǎn huá rú shuǐ", "soft and smooth like water", "lembut dan licin seperti air"],
    ["，", "", "", ""],
    ["不粘牙", "bù zhān yá", "doesn't stick to teeth", "tidak melekat pada gigi"],
    ["、", "", "", ""],
    ["不滞齿", "bù zhì chǐ", "doesn't cling to teeth", "tidak tersekat pada gigi"],
    ["，", "", "", ""],
    ["切片而食", "qiē piàn ér shí", "sliced and eaten", "dipotong dan dimakan"],
    ["，", "", "", ""],
    ["幽香绕舌", "yōu xiāng rào shé", "fragrance lingers on the tongue", "haruman melekat di lidah"],
    ["，", "", "", ""],
    ["那股", "nà gǔ", "that", "rasa"],
    ["适口的甜味", "shì kǒu de tián wèi", "pleasant sweetness", "manis yang sesuai"],
    ["，", "", "", ""],
    ["晃荡晃荡地", "huàng dàng huàng dàng de", "gently", "perlahan-lahan"],
    ["由喉头", "yóu hóu tóu", "from the throat", "dari tekak"],
    ["轻飘飘地", "qīng piāo piāo de", "lightly", "dengan ringan"],
    ["流进了", "liú jìn le", "flowed into", "mengalir ke"],
    ["胃囊里", "wèi náng lǐ", "stomach", "perut"],
    ["，", "", "", ""],
    ["通体舒畅", "tōng tǐ shū chàng", "whole body comfortable", "seluruh badan selesa"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    ["别人", "bié rén", "Others", "Orang lain"],
    ["做年糕", "zuò nián gāo", "making New Year cake", "membuat kuih Tahun Baru"],
    ["，", "", "", ""],
    ["做不出", "zuò bù chū", "couldn't make", "tidak dapat buat"],
    ["同样的水准", "tóng yàng de shuǐ zhǔn", "same standard", "tahap yang sama"],
    ["，", "", "", ""],
    ["登门讨教", "dēng mén tǎo jiào", "came to ask for advice", "datang meminta nasihat"],
    ["，", "", "", ""],
    ["祖母", "zǔ mǔ", "grandmother", "nenek"],
    ["在倾囊相授之余", "zài qīng náng xiāng shòu zhī yú", "after teaching everything", "selepas mengajar segalanya"],
    ["，", "", "", ""],
    ["总会", "zǒng huì", "would always", "akan selalu"],
    ["加上", "jiā shàng", "add", "menambah"],
    ["这几句话", "zhè jǐ jù huà", "these words", "kata-kata ini"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["磨粉的时候", "mó fěn de shí hou", "When grinding the flour", "Ketika mengisar tepung"],
    ["，", "", "", ""],
    ["心", "xīn", "heart", "hati"],
    ["一定要诚", "yí dìng yào chéng", "must be sincere", "mesti ikhlas"],
    ["。", "", "", ""],
    ["年糕小气", "nián gāo xiǎo qì", "New Year cake is sensitive", "Kuih Tahun Baru sensitif"],
    ["，", "", "", ""],
    ["你不诚心", "nǐ bù chéng xīn", "if you're not sincere", "jika awak tidak ikhlas"],
    ["，", "", "", ""],
    ["便做不成它", "biàn zuò bù chéng tā", "you won't make it well", "awak tidak akan berjaya"],
    ["。”", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    ["祖母", "zǔ mǔ", "Grandmother", "Nenek"],
    ["已去世", "yǐ qù shì", "has passed away", "telah meninggal dunia"],
    ["多年了", "duō nián le", "for many years", "bertahun-tahun"],
    ["，", "", "", ""],
    ["然而", "rán ér", "however", "namun"],
    ["，", "", "", ""],
    ["每逢新年", "měi féng xīn nián", "every New Year", "setiap kali Tahun Baru"],
    ["吃年糕时", "chī nián gāo shí", "when eating New Year cake", "apabila makan kuih Tahun Baru"],
    ["，", "", "", ""],
    ["脑海里", "nǎo hǎi lǐ", "in my mind", "dalam fikiran"],
    ["总会浮现", "zǒng huì fú xiàn", "would always appear", "akan terbayang"],
    ["祖母磨粉时", "zǔ mǔ mó fěn shí", "grandmother grinding flour", "nenek mengisar tepung"],
    ["那一张", "nà yì zhāng", "that", "wajah"],
    ["虔诚已极的脸", "qián chéng yǐ jí de liǎn", "extremely pious face", "yang sangat khusyuk"],
    ["，", "", "", ""],
    ["而", "ér", "and", "dan"],
    ["这些年来", "zhè xiē nián lái", "over the years", "sepanjang tahun-tahun ini"],
    ["，", "", "", ""],
    ["“", "", "", ""],
    ["你不诚心", "nǐ bù chéng xīn", "If you are not sincere", "Jika awak tidak ikhlas"],
    ["，", "", "", ""],
    ["便做不成它", "biàn zuò bù chéng tā", "you won't make it", "awak tidak akan berjaya"],
    ["”", "", "", ""],
    ["这两句话", "zhè liǎng jù huà", "these two sentences", "dua ayat ini"],
    ["，", "", "", ""],
    ["也", "yě", "also", "juga"],
    ["成了", "chéng le", "has become", "telah menjadi"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["处世哲学", "chǔ shì zhé xué", "life philosophy", "falsafah hidup"],
    ["之一", "zhī yī", "one of", "salah satu"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", ""],
    ["尤今", "yóu jīn", "You Jin", "You Jin"],
    ["《", "", "", ""],
    ["年糕", "nián gāo", "New Year Cake", "Kuih Tahun Baru"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
